export const API_ROUTES = {
  authLogin: '/auth/login',
  authLogout: '/auth/logout',
  users: '/users',
  userById: (id: number | string) => `/users/${id}`,
  userDashboardEmailPreferenceById: (id: number | string) => `/users/${id}/dashboard-email-preference`,
  profiles: '/profiles',
  profileById: (id: number | string) => `/profiles/${id}`,
  dashboardKpis: '/dashboard/kpis',
  kpiSummaryEmailSchedule: '/email-schedules/kpi-summary',
  platforms: '/platforms',
  platformById: (id: number | string) => `/platforms/${id}`,
  subscribers: '/subscribers',
  subscriberById: (id: number | string) => `/subscribers/${id}`,
  subscriberSubscriptions: (id: number | string) => `/subscribers/${id}/subscriptions`,
  associateSubscriberPlatforms: (id: number | string) => `/subscribers/${id}/associate`,
  disassociateSubscriberPlatforms: (id: number | string) => `/subscribers/${id}/disassociate`,
  subscriberBilling: (id: number | string) => `/billing/${id}`,
  paymentConfirmations: '/subscribers/payments/confirmations',
  approvePaymentConfirmation: (id: number | string) => `/subscribers/payments/confirmations/${id}/approve`,
  pendingPaymentConfirmations: '/subscribers/payments/confirmations/pending',
  sendSubscriberBillingEmail: '/subscribers/billing/email-summary',
  registerSubscriberPayments: (subscriberId: number | string) => `/paymnets/subscribers/${subscriberId}`,
} as const;
